version: 2.1 # CircleCI api version
jobs:
  build:
    docker:
      - image: openjdk:11
    environment:
      - SBT_VERSION: 1.4.2
    steps:
      - run:
          name: Get sbt binary # Download and install sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
      - checkout # Checkout from origin branch
      - setup_remote_docker # Setup remote docker environment
      - run:
          name: Clean # Clean project
          command: sbt clean
      - run:
          name: Compile # Build project
          command: sbt compile
      - run:
          name: Test # Run tests
          command: sbt test
      - run:
          name: Publish # Publish docker container
          command: sbt docker:publish
