version: 2.1 # CircleCI api version
jobs:
  build:
    docker:
      - image: openjdk:11
    environment:
      - SBT_VERSION: 1.4.2
    steps:
      - checkout # Checkout from origin branch
      - run:
          name: Install sbt # Download and install sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
      - run:
          name: Install docker # Download and install docker client
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
      - setup_remote_docker
      - run:
          name: Docker login
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker version --format '{{.Server.APIVersion}}'
      - run:
          name: Clean # Clean project
          command: sbt clean
      - run:
          name: Compile # Build project
          command: sbt compile
      - run:
          name: Test # Run tests
          command: sbt test
      - run:
          name: Publish # Publish docker container
          command: sbt docker:publish
