version: 2.1 # CircleCI api version
jobs:
  build:
    docker:
      - image: openjdk:11
    environment:
      - SBT_VERSION: 1.4.2
    steps:
      - run:
          name: Install sbt # Download and install sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
            dpkg -i sbt-$SBT_VERSION.deb
            rm sbt-$SBT_VERSION.deb
      - run:
          name: Install docker # Download and install docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Docker command docker # Download and install docker client
          command: |
            which docker
      - checkout # Checkout from origin branch
      - run:
          name: Clean # Clean project
          command: sbt clean
      - run:
          name: Compile # Build project
          command: sbt compile
      - run:
          name: Test # Run tests
          command: sbt test
      - run:
          name: Publish # Publish docker container
          command: sbt docker:publish
